// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/26/2026, 11:56:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/marquis/curatewithng/vendor/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/plugins/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/vendor/composables/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/vendor/utils/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/vendor/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/vendor/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;